Repository Voter-Software-Process-2022/voter-frontend, pull requests merged in 2022-10, with the labels that each got.

#7 Fix navbar and add sidebar
  src/components/Navbar.tsx
  src/components/Navbar/index.tsx
  src/components/NavbarLink.tsx
  src/components/Sidebar.tsx
  src/components/SidebarLink.tsx
  src/components/Video.tsx
  src/components/Video/index.tsx
  src/components/index.tsx
  src/config/menu.ts
  src/hooks/useOutsideAlerter.ts
  src/interfaces/components/navbar.ts
  src/interfaces/components/sidebar.ts
  src/interfaces/menu.ts
  src/pages/Home/index.tsx
  tailwind.config.cjs
Labels: invalid, ready to review

#9 Initialize CI/CD Pipeline
  .github/workflows/main.yml
  .github/workflows/pull_request.yml
  .github/workflows/test.yml
  .gitignore
  package-lock.json
  package.json
Labels: ready to review

#10 Register page
  README.md
  package-lock.json
  package.json
  src/hooks/useOutsideAlerter.ts
  src/main.tsx
  src/pages/SignUp/index.tsx
Labels: enhancement, ready to review

#11 Fix image path from assests directory
  src/components/Navbar.tsx
  src/pages/Home/index.tsx
  src/pages/SignUp/index.tsx
Labels: ready to review

#14 Setup vitest for testing and codecov
  .eslintignore
  .eslintrc.yml
  .github/workflows/test.yml
  .gitignore
  .husky/pre-commit
  .prettierignore
  README.md
  index.html
  package-lock.json
  package.json
  postcss.config.cjs
  postcss.config.js
  src/App.tsx
  src/__test__/components/NavbarLink.test.tsx
  src/components/Loader.tsx
  src/components/Navbar.tsx
  src/components/NavbarLink.tsx
  src/components/Sidebar.tsx
  src/components/SidebarLink.tsx
  src/components/Video.tsx
  src/components/index.tsx
  src/config/menu.ts
  src/hooks/useOutsideAlerter.ts
  src/interfaces/menu.ts
  src/pages/Home/index.tsx
  src/pages/SignUp/index.tsx
  src/router/index.tsx
  src/router/routes.tsx
  tailwind.config.js
  tsconfig.json
  tsconfig.node.json
  vite.config.ts
  yarn.lock
Labels: ready to review

#15 Create login page
  src/components/Sidebar.tsx
  src/pages/SignIn/index.tsx
  src/pages/SignUp/index.tsx
  src/router/routes.tsx
  src/utils/alert.ts
Labels: enhancement, ready to review
